# Setting Things Up

To use TorchSharp, you need some packages from NuGet.

First and foremost, you need to download the most recent version of the `TorchSharp` package at [https://www.nuget.org/packages/TorchSharp/](https://www.nuget.org/packages/TorchSharp/). That's the .NET bindings to libtorch, and it contains the .NET API. However, you also need one of several packages containing distributions of libtorch itself, the highly capable native-code engine behind PyTorch.

Starting with version 0.93.4, there are bundled versions of these packages, which is what these tutorials rely on.

The basic backend supports training and inference on CPUs, but there is also support for CUDA on Windows and Linux, for use on machines with compatible hardware. Using CUDA for training can speed things up by orders of magnitude, so it's important to use the right backend.

These are the various libtorch packages:

|Name|URL|Description|
|-----|-----------------|--------------|
|TorchSharp-cpu|https://www.nuget.org/packages/TorchSharp-cpu/|TorchSharp with only the CPU backend, which works on Windows, Linus, and MacOS|
|TorchSharp-cuda-windows|https://www.nuget.org/packages/TorchSharp-cuda-windows/|A CUDA backend with only Windows binaries|
|TorchSharp-cuda-linux|https://www.nuget.org/packages/TorchSharp-cuda-linux/|A CUDA backend with only Linux binaries|

All the tutorial notebooks (with the exception of the one that covers CUDA) will rely on the CPU package, since that takes up the least amount of disk space and works everywhere. If you have access to a CUDA processor, replace the package name with the applicable Windows or Linux package from NuGet (TorchSharp-cuda-windows and TorchSharp-cuda-linux, respectively).

In [1]:
#r "nuget: TorchSharp-cpu"


Installed Packages TorchSharp-cpu, 0.99.4

# Usings

Once you have the right NuGet packages, the next thing is to get the right usings directives at the top of your source files. TorchSharp consists of a lot of namespaces and static classes, and to make programming TorchSharp convenient, you usually need to include a several of them.

In [2]:
using TorchSharp;

using static TorchSharp.torch.nn;
using static TorchSharp.torch.nn.functional;
using static TorchSharp.TensorExtensionMethods;

However, for these tutorials, it would obscure the API to have too many usings. It's better, for pedagogical reasons, to explicitly qualify names until their scope becomes well known. So, the tutorials will generally use a minimal set of usings.

# Formatting

.NET Interactive will, by default, display the fields and properties of the objects that are found at the end of each cell. To make it show a nicely formatted view of the data of a tensor, the following needs to be at the top of each notebook:

In [15]:
using Microsoft.DotNet.Interactive.Formatting;

Formatter.SetPreferredMimeTypesFor(typeof(torch.Tensor), "text/plain");
Formatter.Register<torch.Tensor>((torch.Tensor x) => x.ToString(TorchSharp.TensorStringStyle.Default));

Note that there are two styles that may be used to format tensor output: NumPy-style and Julia-style. Whatever you set it to in the cell at the top will be used to format tensors automatically.

In [16]:
torch.ones(2,3,3)

[2x3x3], type = Float32, device = cpu
[0,..,..] =
 1 1 1
 1 1 1
 1 1 1

[1,..,..] =
 1 1 1
 1 1 1
 1 1 1


 The 'Default' style means that the actual format is picked up at runtime from the global style, which is 'Julia' unless you set it to 'NumPy':    

In [18]:
torch.TensorStringStyle = torch.numpy;

torch.ones(2,3,3)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]